stages:
  - test_and_build

variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
    SCALENODE_CPU: 4
    SCALENODE_RAM: 8192
    SCALENODE_DISK: 15

image: debian:bullseye

before_script:
  - apt-get -y update
  - apt-get -y upgrade

  # Install dependencies
  - apt-get -fy install python python3 python3-pip git build-essential make curl flex bison zlib1g-dev
  - pip3 install -r requirements.txt

test:
  variables:
    SCALENODE_RAM: 16384
  stage: test_and_build
  tags: ["ace-x86_64"]
  script:
    # Install dependencies
    - apt-get install -y autoconf gperf perl autoconf ccache libgoogle-perftools-dev numactl perl-doc libfl2 libfl-dev help2man

    # Install icarus verilog
    - git clone https://github.com/verilator/verilator && cd verilator
    - git checkout master
    - autoconf
    - ./configure
    - make -j $(nproc)
    - make install
    - cd ..

    # Run tests
    - TRACE=1 make tests | tee log.txt
    - '! cat $(find . -name "results.xml") | grep -cq "<failure />"'
  artifacts:
    when: always
    name: tests
    expire_in: 2 weeks
    paths:
      - log.txt
      - results.xml
      - tests/build/

bitstream:
  stage: test_and_build
  tags: ["ace-x86_64"]
  script:
    # Install dependencies
    - apt-get -fy install clang libreadline-dev gawk tcl-dev libffi-dev git graphviz xdot pkg-config libboost-all-dev cmake libeigen3-dev

    # Install Rust
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - source "$HOME/.cargo/env"

    # Install Yosys
    - git clone https://github.com/YosysHQ/yosys.git && cd yosys
    - make config-clang
    - make -j $(nproc)
    - make install
    - cd ..

    # Install prjoxide
    - git clone --recursive https://github.com/gatecat/prjoxide && cd prjoxide
    - cd libprjoxide
    - cargo install --path prjoxide
    - cd ../..

    # Install nextpnr-nexus
    - git clone https://github.com/YosysHQ/nextpnr.git && cd nextpnr
    - cmake -DARCH=nexus -DOXIDE_INSTALL_PREFIX=$HOME/.cargo .
    - make -j $(nproc)
    - cp nextpnr-nexus $HOME/.cargo/bin/
    - export PATH=$PATH:$HOME/.cargo/bin
    - cd ..

    # Build a bistream, specify video format to avoid false negatives
    # related to nextpnr issue: https://github.com/YosysHQ/nextpnr/issues/903
    - LANES=2 VIDEO_FORMAT=1080p_3g NEXTPNR_ARGS="--placer-heap-timingweight 50" make all
  artifacts:
    name: bitstream-build
    expire_in: 2 weeks
    paths:
      - build/
